services:
  mysql:
    image: mysql:8.0.41
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=asy
      - MYSQL_PASSWORD=autumn